const Actions = {
  GET_MENU_HEADER_REQUEST: 'GET_MENU_HEADER_REQUEST',
  GET_MENU_HEADER_RESPONSE: ' GET_MENU_HEADER_RESPONSE',

  getMenuHeader: () => ({
    type: Actions.GET_MENU_HEADER_REQUEST
  }),

  GET_MENU_NAV_REQUEST: 'GET_MENU_NAV_REQUEST',
  GET_MENU_NAV_RESPONSE: 'GET_MENU_NAV_RESPONSE',

  getMenuNav: () => ({
    type: Actions.GET_MENU_NAV_REQUEST
  }),

  GET_MENU_FOOTER_TOP_REQUEST: 'GET_MENU_FOOTER_TOP_REQUEST',
  GET_MENU_FOOTER_TOP_RESPONSE: 'GET_MENU_FOOTER_TOP_RESPONSE',

  getMenuFooterTop: () => ({
    type: Actions.GET_MENU_FOOTER_TOP_REQUEST
  }),

  GET_MENU_FOOTER_MAIN_REQUEST: 'GET_MENU_FOOTER_MAIN_REQUEST',
  GET_MENU_FOOTER_MAIN_RESPONSE: 'GET_MENU_FOOTER_MAIN_RESPONSE',

  getMenuFooterMain: () => ({
    type: Actions.GET_MENU_FOOTER_MAIN_REQUEST
  }),

  GET_MENU_FOOTER_BOTTOM_REQUEST: 'GET_MENU_FOOTER_BOTTOM_REQUEST',
  GET_MENU_FOOTER_BOTTOM_RESPONSE: 'GET_MENU_FOOTER_BOTTOM_RESPONSE',

  getMenuFooterBottom: () => ({
    type: Actions.GET_MENU_FOOTER_BOTTOM_REQUEST
  }),

  GET_MENU_SEARCH_REQUEST: 'GET_MENU_SEARCH_REQUEST',
  GET_MENU_SEARCH_RESPONSE: 'GET_MENU_SEARCH_RESPONSE',

  getMenuSearch: () => ({
    type: Actions.GET_MENU_SEARCH_REQUEST
  })
};

export default Actions;
