const Actions = {
  GET_SETTING_FOOTER_REQUEST: 'GET_SETTING_FOOTER_REQUEST',
  GET_SETTING_FOOTER_RESPONSE: 'GET_SETTING_FOOTER_RESPONSE',

  getSettingFooterAction: () => ({
    type: Actions.GET_SETTING_FOOTER_REQUEST
  }),

  GET_SOCIALINK_REQUEST: 'GET_SOCIALINK_REQUEST',
  GET_SOCIALINK_RESPONSE: 'GET_SOCIALINK_RESPONSE',

  getSocailinkAction: () => ({
    type: Actions.GET_SOCIALINK_REQUEST
  })
};

export default Actions;
